# --------------------------------------------------------
__author__ = "Vladimir Fedorov"
__copyright__ = "Copyright (C) 2013 Migrate2Iaas"
#---------------------------------------------------------

#this module declares various version info
#Note: it (or its back) could be autogenerated

minorVersion = 5
majorVersion = 0
buildtime = "(none)"
revisionhash = "(none)"
branch = "(none)"
revision = "0"

def getFullVersionString():
    return "v"+str(majorVersion)+"."+str(minorVersion) + "." + revision + " built on " + str(buildtime) + " ( branch: " + str(branch) + " hash:" + str(revisionhash) + ")"

def getShortVersionString():
    return "v"+str(majorVersion)+"."+str(minorVersion) + "." + revision 
